from pathlib import Path
from flask import Response, jsonify, request
from backend.config import VIDEOS_DIR, UPLOADS_DIR, OUTPUT_DIR
from . import api_bp

try:
    import video_inference1
except ImportError:
    video_inference1 = None

@api_bp.route("/live_feed/<path:filename>", methods=["GET"])
def live_feed(filename):
    """Stream MJPEG video feed generated by real-time AI detection engine."""
    if not video_inference1 or not hasattr(video_inference1, "generate_live_frames"):
        return Response("Live inference generator unavailable", status=503)

    video_path = None
    if (UPLOADS_DIR / filename).exists():
        video_path = UPLOADS_DIR / filename
    elif (VIDEOS_DIR / filename).exists():
        video_path = VIDEOS_DIR / filename
    elif (OUTPUT_DIR / filename).exists():
        video_path = OUTPUT_DIR / filename
    else:
        sample_fallback = VIDEOS_DIR / "hello.mp4"
        if sample_fallback.exists():
            video_path = sample_fallback

    if not video_path or not video_path.exists():
        return Response("Video feed source not found", status=404)

    return Response(
        video_inference1.generate_live_frames(video_path),
        mimetype="multipart/x-mixed-replace; boundary=frame"
    )
